### ISSUE TITLE
Fret Bug

### ISSUE THREAD

**Issue by pul53gh** [redrockruby/ch-flat-mod#1]
Green and Orange frets appear to be the default fret texture until hitting a note'

Held Down:
![Clone Hero 2021-05-11 12-51-28](https://user-images.githubusercontent.com/75389344/117855107-286c8980-b258-11eb-9342-865d5e3493b2.png)

Playing a note:
![Clone Hero 2021-05-11 12-54-02](https://user-images.githubusercontent.com/75389344/117855135-30c4c480-b258-11eb-8a9a-ac20e34e1e64.png)

**Comment by solamint** [comment]
Oh, I completely forgot about that. Noted.

**Comment by solamint** [comment]
The strikeline in general needs touching up as well, the fret wells on G/O are unedited.

**Comment by solamint** [comment]
Fixed. See new update.
